### PR TITLE
DIT-2387 # made contact telephone number mandatory.

### PR DESCRIPTION
**Pull request by tipperba**

### CODE REVIEW

**Comment by tipperba** [comment]
Converting to draft as needs to be merged at the same time as an equivalent PR on traders frontend, and I have parked that while we clarify whether we need to add phone number validation to the ticket.

**Comment by DavidGregory084** [comment]
@tipperba this will need to be updated in all the frontends, not just trader frontend

**Comment by tipperba** [comment]
Thanks @DavidGregory084 - will make the changes on the other frontends as well.

**Comment by DavidGregory084** [comment]
@tipperba we will need to make sure that we can get this value from the data transformation as well - is it always populated in the migrated data?

it might also be difficult to get this through the pipeline if the ATs don't always populate the value

this is because we won't be able to pass the pipeline for this repo as the acceptance tests will be triggered, which use all of the frontends

**Comment by DavidGregory084** [comment]
in the end it might be easier to leave it optional in the model and keep the validation in the trader frontend only

**Pull request closed without merging**
